realm: oldcity

webserver:
  network: "tcp"
  listen: "127.0.0.1:3000"
  session_secret: "secret"
  session_max_age: "30m"

authenticator:
  ttl: 180s
  connection_string: "ldap://192.168.47.3:389"
  start_tls: false
  insecure_tls: false
  readonly_dn: "cn=readonly,dc=vodolaz095,dc=ru"
  readonly_passwd: "readonly"
  user_base_tpl: "uid=%s,ou=people,dc=vodolaz095,dc=ru"
  groups_ou: "ou=groups,dc=vodolaz095,dc=ru"

tracing:
  endpoint: "192.168.47.3:6831"
  ratio: 1

log:
  level: "trace"
  to_journald: false
