realm: oldcity

webserver:
  network: "tcp"
  listen: "0.0.0.0:3000"
  cookie_name: "nginx_ldap_auth"
  session_secret: "secret"
  session_max_age: "30m"
  profile_prefix: /auth
  subrequest_basic: /subrequest/basic
  subrequest_session: /subrequest/session
  trusted_proxies:
    - 127.0.0.1

authenticator:
  ttl: 180s
  connection_string: "ldap://ldap:389"
  start_tls: false
  insecure_tls: false
  readonly_dn: "cn=readonly,dc=vodolaz095,dc=ru"
  readonly_passwd: "readonly"
  user_base_tpl: "uid=%s,ou=people,dc=vodolaz095,dc=ru"
  groups_ou: "ou=groups,dc=vodolaz095,dc=ru"

tracing:
  protocol: udp
  host: jaeger
  port: 6831
  ratio: 1

permissions:
  - host: localhost:3000
    prefix: /basic
    uids:
      - abeloy
    gids:
      - test
  - host: localhost:3000
    prefix: /private
    uids:
      - abeloy
    gids:
      - test

log:
  level: "trace"
  to_journald: false
