version: "3.11"

volumes:
  ldap:
  slapdd:
  gomodcache:

networks:
  nginx_ldap_auth_network:

services:
  jaeger:
    container_name: jaeger
    image: docker.io/jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686/tcp" # webui is listening
      - "14268:14268/tcp" # accepting spans in compact jaeger thrift format over http
      - "6831:6831/udp" # accepting spans in compact jaeger thrift format over udp
    networks:
      - nginx_ldap_auth_network

  ldap:
    image: docker.io/osixia/openldap:1.4.0
    environment:
      LDAP_ORGANISATION: "OldCity"
      LDAP_DOMAIN: "vodolaz095.ru"
      LDAP_ADMIN_PASSWORD: "someRandomPasswordToMakeHackersSad22223338888"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
    volumes:
      - ldap:/var/lib/ldap
      - slapdd:/etc/ldap/slapd.d
    ports:
      - "1389:389"
      - "1636:636"
    networks:
      - nginx_ldap_auth_network

  lam:
    image: docker.io/ldapaccountmanager/lam:stable
    environment:
      # https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/.env
      LDAP_DOMAIN: "vodolaz095.ru"
      LDAP_ORGANISATION: "OldCity"
      LDAP_ADMIN_PASSWORD: "someRandomPasswordToMakeHackersSad22223338888"
      LDAP_READONLY_USER_PASSWORD: "someRandomPasswordToMakeHackersSad22223338888"
      LDAP_USERS_DN: "ou=people,dc=vodolaz095,dc=ru"
      LDAP_GROUPS_DN: "ou=groups,dc=vodolaz095,dc=ru"
      LDAP_SERVER: "ldap://ldap:389"
      LDAP_USER: "cn=admin,dc=vodolaz095,dc=ru"
      LAM_LANG: "en_US"
      LAM_PASSWORD: "someRandomPasswordToMakeHackersSad22223338888"
    ports:
      - "8085:80"
    networks:
      - nginx_ldap_auth_network

  nginx:
    image: docker.io/library/nginx:1.27-alpine
    ports:
      - "3000:80"
    volumes:
      - type: bind
        source: ./contrib/conf.d/
        target: /etc/nginx/conf.d/
        read_only: true
        bind:
          selinux: Z
      - type: bind
        source: ./contrib/www/
        target: /usr/share/nginx/html/
        read_only: true
        bind:
          selinux: Z
    networks:
      - nginx_ldap_auth_network
    depends_on:
      - nginx-ldap-auth

  nginx-ldap-auth:
    build:
      context: ./
      dockerfile: ./Dockerfile_development
    ports:
      - "3003:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: true
        bind:
          selinux: Z
      - gomodcache:/go/pkg/mod
    networks:
      - nginx_ldap_auth_network
